### ISSUE TITLE
Minor: error: 'Python.h' file not found

### ISSUE THREAD

**Issue by cyphunk** [WiMLDS/deepdream-workshop#1]
If one gets the error

```
$ make pycaffe
say CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
python/caffe/_caffe.cpp:1:10: fatal error: 'Python.h' file not found
```

This has to do with installation of the python-dev package. On my system of homebrew I did not have this. However I added the following include directories to PYTHON_INCLUDES of the Makefile.config to solve this problem.

```
$ python-config --includes
-I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7
```

Remove the `-I` before adding.

**Comment by ledell** [comment]
Thanks for the note!  There were a few people in the workshop that had a similar-looking issue.
